### ISSUE TITLE
tactic to combat imbalance

### ISSUE THREAD

**Issue by bourbe** [diefimov/santander_2016#1]
Hi,

  Have you done something special to treat the fact that this is a very imbalance problem ?

Regads

**Comment by diefimov** [comment]
Nope, just ensembling of many CV folds to reduce the noise.

**Comment by bourbe** [comment]
Ok, thanks 

great job ! 

I am learning a lot with your code. How can I contact ikki for his keras model ? I have some questions ?

**Comment by diefimov** [comment]
His email is specified in the report.

**Comment by ikki407** [comment]
@bourbe If you have any questions please email to ikki0407@gmail.com
