### ISSUE TITLE
How do you come up the idea of the likelihood features equation? Thanks!

### ISSUE THREAD

**Issue by guotong1988** [diefimov/santander_2016#3]
And how the equation should be this?
Also I don't have the intuition of what likelihood feature is. 
Thanks very much.

![2016-11-04 15-15-38](https://cloud.githubusercontent.com/assets/4702353/19997449/9743de24-a2a1-11e6-9cf8-df4d3ce1549b.png)

**Comment by diefimov** [comment]
Regarding the likelihood read about Laplace smoothing.
